### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds a Dockerfile for fast deployment from sources. It relies on an Alpine base image with Go installed. Tell me if you prefer another base image or if you'd prefer to install Go directly in the Dockerfile.

The web interface is exposed on port 8080.

### CODE REVIEW

**Comment by Lesterpig** [comment]
Thanks, good idea!

Several comments here:
- I'm absolutely fine with the alpine image :) However, no need to keep any golang source after the build. Maybe we can remove golang from the container as a last command? I'm not sure it would lower the container size... To be determined!
- Small typo on my name, but you can totally remove the `author` field, as these images should remain private ;)
- No need to setup gopath with the alpine image:

``` bash
docker run -it --rm  golang:alpine /bin/sh  
/go # ls
bin  src
/go # echo $GOPATH
/go
```

**Comment by pchaigno** [comment]
> I'm absolutely fine with the alpine image :) However, no need to keep any golang source after the build. Maybe we can remove golang from the container as a last command? I'm not sure it would lower the container size... To be determined!

I don't think that would reduce the size of the image. Since it works in layers and Go was installed in the base image, we can only increase the final size of the image :/
If the goal here is to minimize the size of the image, other approaches are possible, such as [squashing layers](https://github.com/jwilder/docker-squash) or having a single layer to install, compile, and remove Go.

> Small typo on my name, but you can totally remove the author field, as these images should remain private ;)

Sorry :bow: I removed it altogether.

> No need to setup gopath with the alpine image:

Nice! I missed that. Fixed.

**Comment by Lesterpig** [comment]
Thanks! Merging that ;-)

**Comment by pchaigno** [comment]
:zap:

**Pull request merged**
